[package]
name = "xdg-shell-wrapper-bin"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "xdg-shell-wrapper"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.53"
shlex = "1.1.0"
slog = { version = "2.7.0", features = ["max_level_trace", "release_max_level_warn"] }
slog-term = "2.8.1"
slog-async = "2.7.0"
slog-stdlog = "4.1.0"
slog-scope = "4.4.0"
xdg-shell-wrapper = { path = "./xdg-shell-wrapper" }

