[package]
name = "xdg-shell-wrapper-config"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
wayland-protocols = { version = "0.29" , features = ["client", "unstable_protocols"] }
